'use strict';
/*
 * 빚과 칼 — 내용
 *
 * 이 파일의 핵심은 이벤트 개수가 아니라 flag 로 엮인 그물이다.
 * 아래 선택들은 전부 나중에 되돌아온다:
 *
 *   spared_thief    도둑을 놓아줌      → 산적 길목에서 통행 무료 · 도둑 표식
 *   sold_thief      도둑을 관에 넘김    → 패거리의 보복
 *   gave_priest     사제에게 기부      → 쓰러졌을 때 공짜로 살려준다
 *   cheated_deal    상인을 속임        → 저잣거리에서 값을 올려 받는다
 *   saved_pup       늑대 새끼를 살림    → 숲에서 무리가 갚는다
 *   took_ring       저주받은 반지 챙김  → 밤마다 갉아먹힌다 (푸는 길이 따로 있다)
 *   killed_yield    항복한 자를 벰      → 말이 돈다. 말솜씨로 푸는 길이 막힌다
 *   helped_pilgrim  순례자를 도움      → 후반에 크게 갚는다
 *
 * 그래서 "3일째에 살려보낸 도둑" 같은 선택지가 20일째에 튀어나온다.
 */

const ITEMS = {
  rusty_blade:  { name: '녹슨 검',        desc: '없는 것보단 낫다 · 싸움 판정 +10%' },
  good_sword:   { name: '잘 벼린 검',      desc: '손에 붙는다 · 싸움 판정 +20%' },
  lockpick:     { name: '쇠꼬챙이',        desc: '자물쇠와 주머니 · 손재주 판정 +15%' },
  padded_coat:  { name: '누빈 겉옷',       desc: '한 대는 덜 아프다 · 최대 체력 +2' },
  herb:         { name: '약초 한 줌',      desc: '쓰면 체력이 돌아온다' },
  charm:        { name: '은부적',          desc: '나쁜 것을 밀어낸다' },
  ruin_map:     { name: '낡은 도면',       desc: '폐허에서 헛걸음이 줄어든다' },
  thief_mark:   { name: '도둑들의 표식',    desc: '아는 사람은 안다' },
  priest_token: { name: '사제의 증표',      desc: '신전이 당신을 기억한다' },
  wolf_tooth:   { name: '늑대 이빨',        desc: '숲이 당신을 안다' },
  cursed_ring:  { name: '저주받은 반지',    desc: '값은 나가는데, 밤마다 무겁다' },
  ledger:       { name: '빚쟁이의 장부',    desc: '숫자는 고쳐 쓸 수 있다' },
  pilgrim_seal: { name: '순례자의 인장',    desc: '먼 곳에서도 통한다' },
};

/* 자주 쓰는 조각 */
const fight = (dc, extra = {}) => ({
  stat: 'might', dc,
  itemBonus: { rusty_blade: 0.10, good_sword: 0.20 },
  ...extra,
});

const EVENTS = [

  /* ============ 저잣거리 ============ */
  {
    id: 'town_board', place: 'town', weight: 14,
    title: '일감 게시판',
    text: '벽에 종이 몇 장이 붙어 있다. 하나같이 품삯이 박하다. 그래도 오늘 밥값은 된다.',
    choices: [
      { text: '짐을 나른다 (하루 종일)',
        result: '해 질 때까지 등짐을 졌다. 허리가 펴지지 않는다.',
        effect: { gold: 12, hp: -1 } },
      { text: '하수구의 쥐를 잡는다',
        check: fight(7),
        ok:   { result: '스무 마리쯤 잡아 꼬리를 세어 보였다. 냄새가 며칠 갈 것 같다.',
                effect: { gold: 20 } },
        fail: { result: '어둠 속에서 뭔가 크고 이빨 있는 것에 손을 물렸다.',
                effect: { hp: -3, gold: 6 } } },
      { text: '장부 정리를 대신해 준다',
        req: { stat: { eye: 10 } },
        result: '숫자가 맞지 않는 곳이 세 군데. 말없이 고쳐 놓자 주인이 놀라서 값을 더 얹어 준다.',
        effect: { gold: 25, stat: { eye: 1 } } },
    ],
  },
  {
    id: 'town_merchant', place: 'town', weight: 12,
    title: '헐값에 넘기는 상인',
    text: '수레 하나를 통째로 정리하는 중이다. "떠나야 해서요. 값은 안 봅니다."',
    choices: [
      { text: '누빈 겉옷을 산다 (금화 18)',
        req: { gold: 18 },
        result: '두툼하다. 안감에 누군가의 이름이 수놓여 있다.',
        effect: { gold: -18, item: 'padded_coat', hpMax: 2 } },
      { text: '녹슨 검을 산다 (금화 10)',
        req: { gold: 10 },
        result: '날이 상했지만 자루는 튼튼하다.',
        effect: { gold: -10, item: 'rusty_blade' } },
      { text: '값을 후려친다',
        check: { stat: 'tongue', dc: 10 },
        ok:   { result: '떠나는 사람의 조급함을 파고들었다. 절반 값에 검과 약초를 얹어 받는다.',
                effect: { gold: -5, item: ['rusty_blade', 'herb'] } },
        fail: { result: '"그렇게 급하진 않습니다." 상인의 눈빛이 식는다.',
                effect: { flag: 'cheated_deal' } } },
      { text: '수레에서 하나 슬쩍한다',
        check: { stat: 'hands', dc: 11, itemBonus: { lockpick: 0.15 } },
        ok:   { result: '천 밑으로 손이 들어갔다 나왔다. 아무도 보지 못했다.',
                effect: { item: 'lockpick', flag: 'cheated_deal' } },
        fail: { result: '손목이 잡혔다. 사람들이 모여든다. 물어주고 겨우 빠져나왔다.',
                effect: { gold: -15, flag: ['cheated_deal', 'known_thief'] } } },
    ],
  },
  {
    id: 'town_temple', place: 'town', weight: 14,
    title: '신전 앞',
    text: '헌금함 앞에 늙은 사제가 앉아 있다. 앞을 못 보는 듯한데, 발소리에 고개를 돌린다.\n"빚이 많은 걸음이군."',
    choices: [
      { text: '가진 것에서 얼마쯤 넣는다 (금화 15)',
        req: { gold: 15 },
        result: '사제가 증표 하나를 쥐여 준다. "언제든 오시오. 값은 이미 치렀소."',
        effect: { gold: -15, item: 'priest_token', flag: 'gave_priest' } },
      { text: '상처를 봐 달라고 한다 (금화 10)',
        req: { gold: 10 },
        result: '약 냄새 나는 손이 상처를 훑고 지나간다.',
        effect: { gold: -10, hp: 5 } },
      { text: '헌금함에 손을 댄다',
        check: { stat: 'hands', dc: 13, itemBonus: { lockpick: 0.15 } },
        ok:   { result: '동전 소리 하나 내지 않았다. 사제는 계속 앞을 보고 있다.\n돌아서는 등 뒤로 목소리가 들린다. "…조심히 가시오."',
                effect: { gold: 40, flag: ['robbed_temple', 'known_thief'] } },
        fail: { result: '손목을 붙잡혔다. 앞을 못 보는 게 아니었다.',
                effect: { hp: -2, flag: 'robbed_temple' } } },
      { text: '그냥 지나간다',
        result: '사제가 뒤에서 뭐라고 했지만 듣지 않았다.' },
    ],
  },
  {
    id: 'town_dice', place: 'town', weight: 10,
    title: '주사위판',
    text: '골목 안쪽, 나무 상자 위에서 주사위가 구른다. 판돈이 작지 않다.',
    choices: [
      { text: '판에 낀다 (금화 20)',
        req: { gold: 20 },
        check: { stat: 'eye', dc: 11 },
        ok:   { result: '누가 손목을 어떻게 트는지 세 판 만에 읽었다. 딴 돈을 챙겨 조용히 일어선다.',
                effect: { gold: 45 } },
        fail: { result: '읽었다고 생각한 게 함정이었다. 주머니가 가벼워졌다.',
                effect: { gold: -20 } } },
      { text: '판을 뒤엎고 사기라고 외친다',
        check: fight(11),
        ok:   { result: '상자가 넘어가고 주사위가 굴렀다. 하나는 확실히 무게가 실려 있었다.\n구경꾼들이 돈을 되찾아 주며 몫을 나눠 준다.',
                effect: { gold: 30, flag: 'town_scene' } },
        fail: { result: '셋이 한꺼번에 달려들었다. 골목 바닥에서 한참을 누워 있었다.',
                effect: { hp: -4 } } },
      { text: '외상으로 판에 낀다',
        req: { notFlag: 'owe_gambler' },
        result: '"얼굴은 기억해 두지." 앞의 두 판을 땄다. 세 번째 판에서 전부 잃었다.',
        effect: { gold: 15, debt: 40, flag: 'owe_gambler' } },
      { text: '구경만 한다',
        result: '한참 보고 있으니 어떤 손버릇이 눈에 익는다.',
        effect: { stat: { eye: 1 } } },
    ],
  },
  {
    id: 'town_creditor', place: 'town', weight: 8, dayFrom: 6,
    title: '빚쟁이의 사람',
    text: '어깨가 넓은 사내가 길을 막는다. 손에 장부를 들고 있다.\n"이자 얘기 좀 합시다."',
    choices: [
      { text: '지금 얼마쯤 갚는다 (금화 40)',
        req: { gold: 40 },
        result: '사내가 장부에 줄을 긋는다. 그 줄이 이상하게 시원하다.',
        effect: { gold: -40, debt: -40 } },
      { text: '사정을 말한다',
        check: { stat: 'tongue', dc: 12, flagBonus: { killed_yield: -0.2 } },
        ok:   { result: '사내가 한참 보더니 장부를 덮는다. "다음엔 없소."',
                effect: { debt: -15 } },
        fail: { result: '말이 길어질수록 사내의 표정이 굳었다. 한 대 맞고 끝났다.',
                effect: { hp: -3 } } },
      { text: '장부를 노린다',
        check: { stat: 'hands', dc: 14, itemBonus: { lockpick: 0.15 } },
        ok:   { result: '사내가 침을 뱉으러 고개를 돌린 사이 장부가 품에 들어왔다.\n숫자는 고쳐 쓸 수 있다.',
                effect: { item: 'ledger', debt: -60, flag: 'stole_ledger' } },
        fail: { result: '손이 닿는 순간 손목이 꺾였다. 뼈가 부러지진 않았다. 다행히도.',
                effect: { hp: -5, debt: 20 } } },
    ],
  },
  {
    id: 'town_healer', place: 'town', weight: 9, req: { },
    title: '약방',
    text: '마른 약초 냄새가 가게 밖까지 난다.',
    choices: [
      { text: '치료를 받는다 (금화 12)',
        req: { gold: 12 },
        result: '고름을 짜내고 새 천을 감았다. 아프지만 개운하다.',
        effect: { gold: -12, hp: 6 } },
      { text: '약초를 산다 (금화 8)',
        req: { gold: 8 },
        result: '언제든 쓸 수 있게 기름종이에 쌌다.',
        effect: { gold: -8, item: 'herb' } },
      { text: '약초를 쓴다',
        req: { item: 'herb' },
        result: '씹으니 혀가 얼얼하다. 상처가 조금 아문다.',
        effect: { lose: 'herb', hp: 5 } },
      { text: '그냥 나온다', result: '주머니 사정이 먼저다.' },
    ],
  },

  /* ============ 길 ============ */
  {
    id: 'road_toll', place: 'road', weight: 13, dayFrom: 3,
    title: '교수대 길목',
    text: '나무 아래 세 사람이 앉아 있다. 하나가 일어서며 손을 내민다.\n"통행료 30이다."',
    choices: [
      { text: '순순히 낸다 (금화 30)',
        req: { gold: 30 },
        result: '돈이 손에서 손으로 넘어갔다. 아무 일도 일어나지 않았다.',
        effect: { gold: -30 } },
      { text: '싸운다',
        check: fight(12),
        ok:   { result: '먼저 움직인 쪽이 이겼다. 나머지는 숲으로 달아났다.\n남은 자루에서 돈이 나온다.',
                effect: { gold: 35, hp: -2 } },
        fail: { result: '셋을 혼자 상대할 수는 없었다. 가진 것을 다 털렸다.',
                effect: { hp: -5, gold: -999 } } },
      { text: '깎아 본다',
        req: { stat: { tongue: 12 } },
        result: '"…10만 내고 가라." 웃으며 손을 젓는다. 오늘은 기분이 좋은 모양이다.',
        effect: { gold: -10 } },
      { text: '"그때 그 얼굴이군."',
        req: { flag: 'spared_thief' },
        tag: '아는 얼굴',
        result: '앞에 선 자가 눈을 크게 뜬다. 몇 마디 오가더니 옆으로 비켜선다.\n"길은 그냥 지나가라. 대신 얘기 하나 해 주지 — 서쪽 폐허, 서까래 밑을 봐라."',
        effect: { item: 'ruin_map' } },
      { text: '표식을 보인다',
        req: { item: 'thief_mark' },
        tag: '아는 얼굴',
        result: '손등의 표식을 보이자 셋이 동시에 물러선다. 아무도 눈을 마주치지 않는다.',
        effect: {} },
    ],
  },
  {
    id: 'road_thief', place: 'road', weight: 20, once: true, dayTo: 18,
    title: '붙잡힌 좀도둑',
    text: '길가에 사람들이 모여 있다. 가운데 어린 도둑 하나가 무릎 꿇려 있다.\n"관에 넘기면 손목이 잘려. 당신이 잡았으니 당신이 정해."',
    choices: [
      { text: '놓아준다',
        result: '도둑이 당신을 한참 본다. 이름도 묻지 않고 사라졌다.\n사람들이 혀를 찼지만 아무도 막지는 않았다.',
        effect: { flag: 'spared_thief' } },
      { text: '관에 넘긴다 (사례금 25)',
        result: '돈은 그 자리에서 받았다. 끌려가며 도둑이 뒤를 돌아봤다.\n그 눈을 오래 기억하게 될 것 같다.',
        effect: { gold: 25, flag: 'sold_thief' } },
      { text: '가진 것을 뺏고 놓아준다',
        result: '주머니를 털자 동전 몇 닢과 쇠꼬챙이가 나왔다. 도둑은 아무 말도 하지 않았다.',
        effect: { gold: 10, item: 'lockpick', flag: 'spared_thief' } },
      { text: '베어 버린다',
        req: { stat: { might: 11 } },
        result: '한 번이었다. 사람들이 흩어졌다. 아무도 고맙다고 하지 않았다.',
        effect: { flag: ['killed_yield', 'town_scene'] } },
    ],
  },
  {
    id: 'road_pilgrim', place: 'road', weight: 16, once: true,
    title: '주저앉은 순례자',
    text: '먼 길을 온 차림이다. 발이 부르터 걷지 못한다.\n"미안하지만… 다음 마을까지만."',
    choices: [
      { text: '업고 간다',
        result: '하루를 통째로 썼다. 어깨가 빠질 것 같다.\n헤어지며 순례자가 인장을 쥐여 준다. "이건 먼 곳에서도 통합니다."',
        effect: { hp: -2, item: 'pilgrim_seal', flag: 'helped_pilgrim' } },
      { text: '약초를 나눠 준다',
        req: { item: 'herb' },
        result: '발을 싸매 주자 순례자가 일어선다. 인장을 내민다.',
        effect: { lose: 'herb', item: 'pilgrim_seal', flag: 'helped_pilgrim' } },
      { text: '가진 것을 물어본다',
        check: { stat: 'eye', dc: 10 },
        ok:   { result: '봇짐 안쪽이 묵직하다. 순례자는 순례자가 아니었다.\n말없이 은부적 하나를 건네받고 갈라섰다.',
                effect: { item: 'charm' } },
        fail: { result: '순례자가 웃으며 빈손을 펴 보인다. 정말로 아무것도 없었다.',
                effect: {} } },
      { text: '지나친다',
        result: '뒤에서 부르는 소리가 한참 들렸다.' },
    ],
  },
  {
    id: 'road_caravan', place: 'road', weight: 11,
    title: '호위를 구하는 행상',
    text: '수레 두 대. 사람은 넷. 하나같이 칼을 쥐어 본 적 없는 손이다.\n"이틀 뒤 고개를 넘습니다. 같이 가 주시면…"',
    choices: [
      { text: '호위를 맡는다',
        check: fight(11),
        ok:   { result: '고개에서 둘이 튀어나왔다. 하나를 넘어뜨리자 나머지가 도망쳤다.\n행상이 약속한 것보다 많이 얹어 준다.',
                effect: { gold: 55, hp: -2 } },
        fail: { result: '수레 하나를 지켰고 하나를 잃었다. 품삯은 절반만 받았다.',
                effect: { gold: 20, hp: -4 } } },
      { text: '값을 먼저 올린다',
        req: { stat: { tongue: 11 } },
        check: fight(11),
        ok:   { result: '두 배를 부르고 절반쯤 깎였다. 그래도 처음보다 낫다.\n고개는 조용히 넘었다.',
                effect: { gold: 70 } },
        fail: { result: '값은 올렸는데 몸이 못 따라줬다. 얼굴을 들 수 없었다.',
                effect: { gold: 25, hp: -4 } } },
      { text: '수레 안을 봐 둔다',
        check: { stat: 'eye', dc: 12 },
        ok:   { result: '천 밑에 신고하지 않은 물건이 있다. 그 사실만으로 값이 오른다.',
                effect: { gold: 40, flag: 'knows_secret' } },
        fail: { result: '들여다보는 걸 들켰다. 호위 얘기는 없던 일이 됐다.',
                effect: { flag: 'cheated_deal' } } },
      { text: '거절한다', result: '고개는 위험하다. 오늘은 아니다.' },
    ],
  },
  {
    id: 'road_corpse', place: 'road', weight: 9,
    title: '길가의 주검',
    text: '죽은 지 하루쯤 됐다. 짐승이 아직 손대지 않았다.',
    choices: [
      { text: '뒤진다',
        check: { stat: 'eye', dc: 9 },
        ok:   { result: '장화 안쪽에서 접어 넣은 동전 주머니가 나왔다.',
                effect: { gold: 30 } },
        fail: { result: '이미 누가 다녀갔다. 남은 건 냄새뿐이다.',
                effect: { hp: -1 } } },
      { text: '묻어 준다',
        result: '맨손으로 팠다. 손톱이 깨졌다. 그래도 해야 할 일 같았다.',
        effect: { hp: -1, flag: 'buried_dead' } },
      { text: '반지를 뺀다',
        result: '손가락이 굳어 잘 빠지지 않았다. 반지는 무겁고, 이상하게 따뜻하다.',
        effect: { item: 'cursed_ring', flag: 'took_ring' } },
      { text: '지나간다', result: '볼 것도 아니다.' },
    ],
  },

  /* ============ 숲 ============ */
  {
    id: 'forest_herb', place: 'forest', weight: 13,
    title: '약초 자리',
    text: '축축한 그늘. 값나가는 잎이 무더기로 자라 있다.',
    choices: [
      { text: '조심히 캔다',
        check: { stat: 'hands', dc: 9 },
        ok:   { result: '뿌리째 상하지 않게 캤다. 약방에서 값을 제대로 쳐줄 것이다.',
                effect: { gold: 28, item: 'herb' } },
        fail: { result: '서두르다 뿌리를 끊었다. 반값도 못 받겠다.',
                effect: { gold: 10 } } },
      { text: '전부 뽑는다',
        result: '자루가 가득 찼다. 내년에 여기엔 아무것도 안 자랄 것이다.',
        effect: { gold: 40, flag: 'stripped_grove' } },
      { text: '쓸 만큼만 캔다',
        result: '두 줌만 캐고 나머지는 두었다.',
        effect: { gold: 14, item: 'herb', flag: 'kept_grove' } },
    ],
  },
  {
    id: 'forest_wolf', place: 'forest', weight: 20, once: true,
    title: '덫에 걸린 것',
    text: '쇠덫에 늑대 새끼가 물려 있다. 다리가 이미 상했다.\n덤불 너머에서 무언가 큰 것이 이쪽을 보고 있다.',
    choices: [
      { text: '덫을 벌려 풀어 준다',
        check: { stat: 'might', dc: 10 },
        ok:   { result: '쇠가 벌어지고 새끼가 절뚝이며 덤불로 사라졌다.\n덤불 속의 눈이 한참 있다가 따라 사라졌다.',
                effect: { flag: 'saved_pup', item: 'wolf_tooth' } },
        fail: { result: '덫은 벌어지지 않았고 손만 찢겼다. 결국 놓아주지 못했다.',
                effect: { hp: -3 } } },
      { text: '가죽만 챙긴다',
        result: '어린 가죽은 값이 좋다. 뒤에서 무언가 낮게 울었다.',
        effect: { gold: 25, flag: 'killed_pup' } },
      { text: '덫만 챙겨 간다',
        result: '쇠는 쇠값이라도 한다. 새끼는 그대로 두었다.',
        effect: { gold: 12 } },
      { text: '물러난다', result: '덤불 속의 것이 더 신경 쓰였다.' },
    ],
  },
  {
    id: 'forest_hunter', place: 'forest', weight: 10,
    title: '사냥꾼의 오두막',
    text: '연기가 오른다. 안에서 목소리가 들린다. "누구요."',
    choices: [
      { text: '하룻밤 재워 달라고 한다',
        check: { stat: 'tongue', dc: 9, flagBonus: { killed_yield: -0.15 } },
        ok:   { result: '말린 고기와 불. 오랜만에 제대로 잤다.',
                effect: { hp: 4 } },
        fail: { result: '문이 닫혔다. 빗장 지르는 소리가 났다.',
                effect: { hp: -1 } } },
      { text: '사냥을 배운다 (금화 20)',
        req: { gold: 20 },
        result: '활은 못 배웠지만 발자국 읽는 법을 배웠다.',
        effect: { gold: -20, stat: { eye: 2 } } },
      { text: '늑대 이빨을 보인다',
        req: { item: 'wolf_tooth' },
        tag: '아는 얼굴',
        result: '사냥꾼이 이빨을 보고 눈을 좁힌다. "…그 무리 것이군."\n말이 길어졌다. 헤어질 때 잘 벼린 검 한 자루를 받았다.',
        effect: { item: 'good_sword' } },
    ],
  },
  {
    id: 'forest_boar', place: 'forest', weight: 11,
    title: '멧돼지',
    text: '덤불이 터지듯 갈라지며 튀어나왔다. 피할 곳이 없다.',
    choices: [
      { text: '맞선다',
        check: fight(12),
        ok:   { result: '옆으로 흘리며 목을 그었다. 고기값이 꽤 나가겠다.',
                effect: { gold: 45, hp: -2 } },
        fail: { result: '어깨를 들이받혔다. 나무에 부딪혀 한참 숨이 안 쉬어졌다.',
                effect: { hp: -4 } } },
      { text: '나무에 오른다',
        check: { stat: 'hands', dc: 10 },
        ok:   { result: '가지에 매달려 한참을 버텼다. 멧돼지는 결국 갔다.',
                effect: { hp: -1 } },
        fail: { result: '손이 미끄러졌다. 떨어지면서 발목이 크게 접질렸다.',
                effect: { hp: -4 } } },
      { text: '늑대 이빨을 꺼내 든다',
        req: { flag: 'saved_pup' },
        tag: '아는 얼굴',
        result: '덤불 세 곳이 동시에 움직였다. 멧돼지가 먼저 알아채고 달아난다.\n회색 등들이 나타났다가, 보지도 않고 사라졌다.',
        effect: { gold: 20 } },
    ],
  },
  {
    id: 'forest_shrine', place: 'forest', weight: 8,
    title: '숲의 낡은 사당',
    text: '이끼에 덮인 돌 사당. 안에 마른 공물이 놓여 있다.',
    choices: [
      { text: '공물을 올린다 (금화 10)',
        req: { gold: 10 },
        result: '바람이 한 번 크게 지나갔다. 몸이 조금 가벼워진 것 같다.',
        effect: { gold: -10, hpMax: 1, hp: 3 } },
      { text: '공물을 가져간다',
        result: '마른 과일과 동전 몇 닢. 돌아서는데 뒤통수가 서늘하다.',
        effect: { gold: 18, flag: 'robbed_shrine' } },
      { text: '반지를 올린다',
        req: { item: 'cursed_ring' },
        tag: '푸는 길',
        result: '반지를 내려놓자 손이 갑자기 가벼워졌다.\n돌 틈으로 무언가 굴러 나온다 — 은부적이다.',
        effect: { lose: 'cursed_ring', item: 'charm', flag: 'ring_freed' } },
    ],
  },

  /* ============ 폐허 ============ */
  {
    id: 'ruin_gate', place: 'ruin', weight: 13,
    title: '무너진 문',
    text: '돌더미가 입구를 반쯤 막았다. 안쪽은 어둡고, 바람이 나온다.',
    choices: [
      { text: '치우고 들어간다',
        check: { stat: 'might', dc: 10 },
        ok:   { result: '돌을 밀어내고 몸을 밀어 넣었다. 안쪽 방에 손대지 않은 궤짝이 있다.',
                effect: { gold: 50, hp: -1 } },
        fail: { result: '돌이 무너지며 정강이를 덮쳤다. 오늘은 여기까지다.',
                effect: { hp: -4 } } },
      { text: '틈으로 기어든다',
        check: { stat: 'hands', dc: 11 },
        ok:   { result: '어깨를 빼고 겨우 통과했다. 좁은 만큼 아무도 들어온 적이 없다.',
                effect: { gold: 60 } },
        fail: { result: '중간에 끼었다. 빠져나오는 데만 한참 걸렸다.',
                effect: { hp: -2 } } },
      { text: '도면을 펴 본다',
        req: { item: 'ruin_map' },
        tag: '아는 길',
        result: '도면대로면 문으로 들어갈 이유가 없다. 서까래 밑에 다른 구멍이 있다.\n곧장 안쪽 방으로 떨어졌다.',
        effect: { gold: 80 } },
    ],
  },
  {
    id: 'ruin_goblin', place: 'ruin', weight: 12,
    title: '먼저 와 있던 것들',
    text: '작은 것 넷이 불 앞에 모여 있다. 가운데 자루가 놓여 있다.',
    choices: [
      { text: '덮친다',
        check: fight(13),
        ok:   { result: '불을 걷어차고 뛰어들었다. 셋이 달아나고 자루가 남았다.',
                effect: { gold: 55, hp: -3 } },
        fail: { result: '수가 많았다. 돌과 몽둥이에 밀려 밖으로 쫓겨났다.',
                effect: { hp: -4 } } },
      { text: '기다렸다가 자루만 챙긴다',
        check: { stat: 'eye', dc: 12 },
        ok:   { result: '불이 사그라들 때까지 기다렸다. 자루는 조용히 따라왔다.',
                effect: { gold: 45 } },
        fail: { result: '발밑에서 돌이 굴렀다. 넷이 동시에 고개를 들었다.',
                effect: { hp: -4, gold: 10 } } },
      { text: '먹을 것을 던져 준다',
        req: { item: 'herb' },
        result: '자루를 하나 던지자 소란이 잦아든다. 길을 비켜 준다.\n지나가며 보니 자루 안엔 별것 없었다. 다만 벽에 그려진 표시가 눈에 남는다.',
        effect: { lose: 'herb', item: 'ruin_map' } },
      { text: '물러난다', result: '넷은 많다.' },
    ],
  },
  {
    id: 'ruin_trap', place: 'ruin', weight: 11,
    title: '바닥이 이상하다',
    text: '복도 한가운데, 돌 색이 미묘하게 다르다.',
    choices: [
      { text: '살펴본다',
        check: { stat: 'eye', dc: 10 },
        ok:   { result: '눌리는 돌이다. 옆으로 돌아가자 그 너머에 아무도 못 가져간 것이 있다.',
                effect: { gold: 55 } },
        fail: { result: '살핀다고 살폈는데 밟았다. 창이 옆구리를 스쳤다.',
                effect: { hp: -5 } } },
      { text: '그냥 밟고 지나간다',
        result: '아무 일도 없었다. 아무 일도 없어서 더 소름이 끼쳤다.',
        effect: { hp: -1 } },
      { text: '쇠꼬챙이로 눌러 본다',
        req: { item: 'lockpick' },
        result: '꼬챙이가 딸깍 걸린다. 장치를 죽여 놓고 편히 지나갔다.\n건너편 벽감에 손대지 않은 것이 있다.',
        effect: { gold: 65 } },
    ],
  },
  {
    id: 'ruin_vault', place: 'ruin', weight: 9, dayFrom: 8,
    title: '잠긴 문',
    text: '쇠문이다. 자물쇠는 아직 살아 있다. 뒤가 조용하다는 게 오히려 수상하다.',
    choices: [
      { text: '딴다',
        check: { stat: 'hands', dc: 14, itemBonus: { lockpick: 0.2 } },
        ok:   { result: '세 번째 시도에서 걸림쇠가 넘어갔다. 안쪽은… 값을 세다 말았다.',
                effect: { gold: 120 } },
        fail: { result: '꼬챙이가 부러졌다. 소리를 들은 무언가가 안쪽에서 문을 두드린다.',
                effect: { hp: -3, lose: 'lockpick' } } },
      { text: '부순다',
        check: fight(14),
        ok:   { result: '경첩째 뜯어냈다. 어깨가 나갈 뻔했지만 값은 했다.',
                effect: { gold: 100, hp: -3 } },
        fail: { result: '문은 멀쩡하고 어깨만 상했다.',
                effect: { hp: -5 } } },
      { text: '표식을 새긴다',
        req: { item: 'thief_mark' },
        tag: '아는 얼굴',
        result: '문설주에 표식을 새기고 물러났다.\n사흘 뒤, 여관 문 앞에 자루 하나가 놓여 있었다. 몫이 정확했다.',
        effect: { gold: 90 } },
    ],
  },
  {
    id: 'ruin_ring', place: 'ruin', weight: 8, once: true, dayFrom: 5,
    title: '벽감 속의 손',
    text: '벽 안쪽 우묵한 곳에 마른 손이 놓여 있다. 손가락 하나에 반지가 끼워져 있다.\n이상하게, 반지만 먼지가 없다.',
    choices: [
      { text: '가져간다',
        result: '빼내자 손이 재가 되어 무너졌다. 반지는 따뜻하다.',
        effect: { item: 'cursed_ring', flag: 'took_ring' } },
      { text: '부적으로 눌러 둔다',
        req: { item: 'charm' },
        result: '은부적을 얹자 반지가 식는다. 벽감을 돌로 막고 나왔다.',
        effect: { lose: 'charm', gold: 30, flag: 'sealed_ring' } },
      { text: '건드리지 않는다',
        result: '먼지가 없다는 건 무언가가 계속 닦고 있다는 뜻이다.' },
    ],
  },

  {
    id: 'road_bridge', place: 'road', weight: 11,
    title: '무너진 다리',
    text: '개울이 불었다. 다리는 반쯤 떠내려갔고, 건너편에 사람들이 서성인다.',
    choices: [
      { text: '건너는 것을 돕고 값을 받는다',
        check: { stat: 'might', dc: 10 },
        ok:   { result: '넷을 업어 건넸다. 마지막 사람이 값을 두 배로 쳐줬다.',
                effect: { gold: 35, hp: -1 } },
        fail: { result: '중간에 발을 헛디뎠다. 둘 다 물에 빠졌다. 값은 못 받았다.',
                effect: { hp: -3 } } },
      { text: '다리를 고친다',
        req: { stat: { hands: 11 } },
        result: '통나무를 걸치고 밧줄로 묶었다. 지나는 사람마다 동전을 놓고 간다.',
        effect: { gold: 40, stat: { hands: 1 } } },
      { text: '돌아간다',
        result: '반나절을 더 걸었다. 발바닥이 화끈거린다.',
        effect: { hp: -1 } },
    ],
  },
  {
    id: 'road_soldier', place: 'road', weight: 10,
    title: '탈영병',
    text: '갑옷 조각을 아직 걸치고 있다. 눈이 풀렸는데 손에는 창이 있다.\n"먹을 것."',
    choices: [
      { text: '가진 것을 나눈다 (금화 10)',
        req: { gold: 10 },
        result: '탈영병이 한참 먹더니 창을 내려놓는다.\n"…서쪽으로 가지 마시오. 거기 뭐가 있소." 그러곤 걸어갔다.',
        effect: { gold: -10, item: 'ruin_map' } },
      { text: '창을 뺏는다',
        check: fight(11),
        ok:   { result: '창은 못 쓰게 됐지만 갑옷 조각은 값이 나갔다.',
                effect: { gold: 30, hp: -2 } },
        fail: { result: '눈이 풀린 것과 못 싸우는 것은 다른 얘기였다.',
                effect: { hp: -4 } } },
      { text: '말을 붙인다',
        check: { stat: 'tongue', dc: 10 },
        ok:   { result: '한참 들어 줬다. 헤어지며 품에서 은부적을 꺼내 준다.\n"이건 이제 나한텐 소용없소."',
                effect: { item: 'charm' } },
        fail: { result: '말이 통하는 상태가 아니었다. 조용히 물러났다.', effect: {} } },
    ],
  },
  {
    id: 'road_toll_officer', place: 'road', weight: 9, dayFrom: 5,
    title: '관문',
    text: '관리가 통행첩을 요구한다. 당신에겐 없다.',
    choices: [
      { text: '통행세를 낸다 (금화 25)',
        req: { gold: 25 },
        result: '도장 하나 찍는 데 25다. 종이가 얇다.',
        effect: { gold: -25 } },
      { text: '둘러댄다',
        check: { stat: 'tongue', dc: 12, flagBonus: { known_thief: -0.2 } },
        ok:   { result: '한참 떠들자 관리가 손을 젓는다. "가시오, 가."', effect: {} },
        fail: { result: '이름과 얼굴이 장부에 올라갔다. 좋을 게 없다.',
                effect: { gold: -15, flag: 'on_the_list' } } },
      { text: '인장을 보인다',
        req: { item: 'pilgrim_seal' },
        tag: '아는 얼굴',
        result: '관리가 인장을 보더니 자세를 고친다. 통행첩을 그냥 써 준다.',
        effect: { flag: 'has_pass' } },
      { text: '밤에 몰래 넘는다',
        check: { stat: 'hands', dc: 12 },
        ok:   { result: '담을 넘는 데 반각도 안 걸렸다.', effect: {} },
        fail: { result: '개가 짖었다. 달아나느라 짐 절반을 버렸다.',
                effect: { gold: -20, hp: -2 } } },
    ],
  },

  {
    id: 'forest_charcoal', place: 'forest', weight: 11,
    title: '숯가마',
    text: '연기가 며칠째 오르는 가마. 숯쟁이가 혼자 일한다. 일손이 모자란 티가 난다.',
    choices: [
      { text: '하루 거든다',
        result: '온몸이 검어졌다. 품삯은 정직하게 쳐줬다.',
        effect: { gold: 22, hp: -1 } },
      { text: '숯을 받아다 판다',
        check: { stat: 'tongue', dc: 10 },
        ok:   { result: '외상으로 받아다 저잣거리에 넘겼다. 차익이 남았다.',
                effect: { gold: 40 } },
        fail: { result: '값이 생각만큼 안 나왔다. 외상값만 겨우 갚았다.',
                effect: { gold: 5 } } },
      { text: '가마 자리를 봐 둔다',
        req: { stat: { eye: 12 } },
        result: '연기 방향으로 바람길을 읽었다. 숲에서 길 잃을 일이 줄겠다.',
        effect: { stat: { eye: 1 }, flag: 'reads_forest' } },
    ],
  },
  {
    id: 'forest_mire', place: 'forest', weight: 10,
    title: '수렁',
    text: '이끼가 덮여 있어 땅인 줄 알았다. 무릎까지 빠졌다.',
    choices: [
      { text: '힘으로 빠져나온다',
        check: { stat: 'might', dc: 10 },
        ok:   { result: '한쪽 신을 버리고 기어 나왔다.', effect: { hp: -1 } },
        fail: { result: '허우적댈수록 깊어졌다. 겨우 나왔을 땐 해가 기울어 있었다.',
                effect: { hp: -4, gold: -10 } } },
      { text: '천천히 눕듯이 빠져나온다',
        req: { stat: { eye: 10 } },
        result: '몸을 눕혀 무게를 펴자 수렁이 놓아 줬다. 침착함이 힘보다 낫다.',
        effect: { stat: { eye: 1 } } },
      { text: '수렁 바닥을 더듬는다',
        check: { stat: 'hands', dc: 12 },
        ok:   { result: '뼈와 함께 가죽 주머니가 잡혔다. 안에 동전이 가득하다.',
                effect: { gold: 70, hp: -2 } },
        fail: { result: '잡힌 건 뼈뿐이었다. 손을 씻어도 냄새가 안 빠진다.',
                effect: { hp: -3 } } },
    ],
  },
  {
    id: 'forest_witch', place: 'forest', weight: 9, dayFrom: 6,
    title: '숲 안쪽의 오두막',
    text: '창에 마른 것들이 잔뜩 걸려 있다. 안에서 여자가 내다본다.\n"뭘 안고 왔누."',
    choices: [
      { text: '상처를 보인다 (금화 15)',
        req: { gold: 15 },
        result: '뜨거운 것을 상처에 붓는다. 비명이 절로 났지만 다음 날 거짓말처럼 나았다.',
        effect: { gold: -15, hp: 8 } },
      { text: '반지를 보인다',
        req: { item: 'cursed_ring' },
        tag: '푸는 길',
        result: '여자가 혀를 찬다. "이걸 왜 끼고 다녀." 손가락을 기름에 담그자 반지가 툭 빠졌다.\n"값은 이걸로 하지." 반지를 가져갔다.',
        effect: { lose: 'cursed_ring', gold: 50, flag: 'ring_freed' } },
      { text: '앞날을 묻는다',
        check: { stat: 'eye', dc: 11 },
        ok:   { result: '알아들을 수 없는 말 사이에 쓸모 있는 게 섞여 있었다.\n어디를 파야 하는지 알겠다.',
                effect: { item: 'ruin_map' } },
        fail: { result: '한참 듣고 나니 남은 건 두통뿐이다.', effect: { hp: -1 } } },
      { text: '물러난다', result: '창에 걸린 것 중 몇은 사람 손 같았다.' },
    ],
  },

  {
    id: 'ruin_well', place: 'ruin', weight: 11,
    title: '마른 우물',
    text: '두레박줄이 아직 걸려 있다. 아래는 보이지 않는다.',
    choices: [
      { text: '내려간다',
        check: { stat: 'hands', dc: 11 },
        ok:   { result: '바닥에 뼈와 함께 던져 넣은 것들이 쌓여 있었다. 동전이 섞여 있다.',
                effect: { gold: 65, hp: -1 } },
        fail: { result: '줄이 삭아 있었다. 중간에서 끊어졌다.',
                effect: { hp: -5 } } },
      { text: '돌을 던져 깊이를 잰다',
        result: '한참 뒤에 소리가 났다. 내려갈 깊이가 아니다.',
        effect: { stat: { eye: 1 } } },
      { text: '두레박줄만 챙긴다',
        result: '삭았지만 짧게 잘라 쓰면 쓸 만하다.',
        effect: { gold: 8 } },
    ],
  },
  {
    id: 'ruin_scribe', place: 'ruin', weight: 10, dayFrom: 4,
    title: '무너진 서고',
    text: '천장이 내려앉아 책이 젖었다. 그래도 몇 권은 멀쩡하다.',
    choices: [
      { text: '값나갈 만한 것을 고른다',
        check: { stat: 'eye', dc: 12 },
        ok:   { result: '세 권을 골랐다. 저잣거리에서 부르는 값이 놀라웠다.',
                effect: { gold: 75 } },
        fail: { result: '한 자루 지고 나왔는데 죄다 젖어 붙어 있었다.',
                effect: { gold: 12, hp: -1 } } },
      { text: '읽어 본다',
        result: '먼지 냄새 나는 글자를 한나절 들여다봤다. 머리가 트인다.',
        effect: { stat: { eye: 2 }, hp: -1 } },
      { text: '셈법 책을 찾는다',
        req: { stat: { eye: 11 } },
        result: '이자 계산이 적힌 장을 찢어 품에 넣었다. 빚쟁이 앞에서 쓸 데가 있겠다.',
        effect: { stat: { tongue: 1 }, flag: 'knows_interest' } },
    ],
  },
  {
    id: 'ruin_rival', place: 'ruin', weight: 10, dayFrom: 6,
    title: '먼저 온 사람',
    text: '횃불 하나가 안쪽에서 움직인다. 사람이다. 이쪽을 봤다.\n둘 다 같은 걸 노리고 왔다.',
    choices: [
      { text: '반씩 나누자고 한다',
        check: { stat: 'tongue', dc: 11, flagBonus: { killed_yield: -0.25 } },
        ok:   { result: '둘이 하니 훨씬 빨랐다. 몫은 정확히 반이었고, 이름도 알게 됐다.',
                effect: { gold: 55, flag: 'made_partner' } },
        fail: { result: '말이 끝나기 전에 상대가 안쪽으로 뛰었다. 남은 건 부스러기다.',
                effect: { gold: 10 } } },
      { text: '먼저 덤빈다',
        check: fight(12),
        ok:   { result: '상대가 횃불을 버리고 달아났다. 짐까지 두고 갔다.',
                effect: { gold: 70, hp: -3 } },
        fail: { result: '상대가 더 익숙했다. 어둠 속에서 한참 헤맸다.',
                effect: { hp: -4, gold: -15 } } },
      { text: '뒤를 밟는다',
        check: { stat: 'eye', dc: 12 },
        ok:   { result: '상대가 아는 길을 그대로 외웠다. 값나가는 건 그 뒤에 챙겼다.',
                effect: { gold: 60, item: 'ruin_map' } },
        fail: { result: '발소리를 들켰다. 상대는 사라지고 길만 남았다.',
                effect: {} } },
    ],
  },
  {
    id: 'ruin_altar', place: 'ruin', weight: 9, dayFrom: 8,
    title: '내려앉은 제단',
    text: '돌판 위에 아직 무언가 놓여 있다. 공기가 차다.',
    choices: [
      { text: '가져간다',
        result: '금붙이다. 값은 확실하다. 등 뒤가 서늘한 것도 확실하다.',
        effect: { gold: 85, hp: -2, flag: 'robbed_altar' } },
      { text: '증표를 올려 둔다',
        req: { item: 'priest_token' },
        tag: '아는 얼굴',
        result: '증표를 올리자 차던 공기가 풀린다. 돌판 아래에서 상자가 밀려 나왔다.',
        effect: { lose: 'priest_token', gold: 110 } },
      { text: '부적으로 눌러 두고 챙긴다',
        req: { item: 'charm' },
        result: '부적을 얹고 금붙이만 걷어 왔다. 뒤가 조용하다.',
        effect: { lose: 'charm', gold: 85 } },
      { text: '두고 나온다', result: '값이 아무리 나가도 안 되는 게 있다.' },
    ],
  },

  /* ============ 과거가 되돌아오는 것들 ============ */
  {
    id: 'cb_thief_gang', place: 'road', weight: 34, once: true, dayFrom: 5,
    req: { flag: 'sold_thief' },
    title: '기다리고 있던 자들',
    text: '길 양쪽에서 동시에 나왔다. 넷이다. 하나가 손목을 들어 보인다 — 잘린 자리다.\n"기억나나."',
    choices: [
      { text: '싸운다',
        check: fight(15),
        ok:   { result: '넷을 상대로 살아남았다. 살아남기만 했다.',
                effect: { hp: -5 } },
        fail: { result: '가진 것을 다 두고 왔다. 걷는 데만 한나절이 걸렸다.',
                effect: { hp: -5, gold: -999 } } },
      { text: '값을 치른다',
        req: { gold: 60 },
        result: '"손목값이다." 세어 보지도 않고 가져갔다.',
        effect: { gold: -60 } },
      { text: '빌 수 있는 만큼 빈다',
        check: { stat: 'tongue', dc: 15, flagBonus: { killed_yield: -0.25, buried_dead: 0.1 } },
        ok:   { result: '한참 뒤 하나가 침을 뱉고 돌아섰다. "다음은 없다."',
                effect: { hp: -2 } },
        fail: { result: '말은 하나도 통하지 않았다.',
                effect: { hp: -4, gold: -40 } } },
    ],
  },
  {
    id: 'cb_thief_help', place: 'town', weight: 34, once: true, dayFrom: 6,
    req: { flag: 'spared_thief', notFlag: 'thief_repaid' },
    title: '골목에서 부르는 소리',
    text: '어깨를 잡혔다. 돌아보니 낯이 익다. 그때보다 옷이 낫다.\n"…아직 안 죽었네."',
    choices: [
      { text: '무슨 일이냐고 묻는다',
        result: '도둑이 손등에 새긴 표식을 보여 준다. "이거 있으면 우리 쪽은 안 건드려."\n표식을 새겨 주고, 동전 주머니도 하나 쥐여 준다.',
        effect: { item: 'thief_mark', gold: 40, flag: 'thief_repaid' } },
      { text: '일을 하나 달라고 한다',
        check: { stat: 'hands', dc: 11, itemBonus: { lockpick: 0.15 } },
        ok:   { result: '창고 하나를 같이 털었다. 몫은 정확히 반이었다.',
                effect: { gold: 90, item: 'thief_mark', flag: 'thief_repaid' } },
        fail: { result: '손이 굼떴다. 몫은 받았지만 다음은 없을 것 같다.',
                effect: { gold: 25, hp: -2, flag: 'thief_repaid' } } },
      { text: '모르는 척한다',
        result: '도둑이 잠깐 서 있다가 골목으로 사라졌다.',
        effect: { flag: 'thief_repaid' } },
    ],
  },
  {
    id: 'cb_priest_save', place: 'town', weight: 34, once: true,
    req: { flag: 'gave_priest' }, dayFrom: 4,
    title: '신전의 문이 열려 있다',
    text: '몸이 성치 않은 채로 지나가는데, 안에서 누가 부른다.\n"들어오시오. 값은 이미 치렀다고 했잖소."',
    choices: [
      { text: '들어간다',
        result: '사흘 잘 것을 하룻밤에 잤다. 나올 때 몸이 제 것 같았다.',
        effect: { hp: 99, hpMax: 1 } },
      { text: '증표를 돌려주고 돈을 청한다',
        req: { item: 'priest_token' },
        result: '사제가 한참 말이 없다가 헌금함을 열어 준다.\n"필요하면 가져가시오. 다만 증표는 두고 가시오."',
        effect: { lose: 'priest_token', gold: 70, hp: 4 } },
    ],
  },
  {
    id: 'cb_cheated', place: 'town', weight: 28, dayFrom: 5,
    req: { flag: 'cheated_deal' },
    title: '값을 안 부르는 가게',
    text: '들어서자 주인이 고개를 든다. 표정이 굳는다.\n"…아, 그쪽이시군요."',
    choices: [
      { text: '비싸게라도 산다',
        req: { gold: 30 },
        result: '두 배를 부르는데 깎아 주지 않는다. 필요한 건 필요한 거다.',
        effect: { gold: -30, item: 'herb', hp: 4 } },
      { text: '사과한다',
        check: { stat: 'tongue', dc: 13 },
        ok:   { result: '한참 듣더니 주인이 한숨을 쉰다. "다음부턴 그러지 마쇼."\n값이 제자리로 돌아왔다.',
                effect: { flag: 'forgiven_deal', item: 'herb' } },
        fail: { result: '말이 끝나기 전에 문을 가리켰다.',
                effect: {} } },
      { text: '그냥 나온다', result: '살 곳은 여기만 있는 게 아니다.' },
    ],
  },
  {
    id: 'cb_ring_night', place: 'road', weight: 30,
    req: { flag: 'took_ring', item: 'cursed_ring', notFlag: 'ring_freed' },
    title: '반지가 무겁다',
    text: '어젯밤에도 같은 꿈이었다. 손가락이 아니라 손 전체가 무겁다.\n반지는 빠지지 않는다.',
    choices: [
      { text: '참는다',
        result: '하루 종일 손이 저렸다. 값은 나가겠지. 아마도.',
        effect: { hp: -3 } },
      { text: '팔아 치운다',
        check: { stat: 'tongue', dc: 12 },
        ok:   { result: '아무것도 모르는 상인에게 넘겼다. 손이 갑자기 가벼워졌다.\n돌아 나오며 뒤가 조금 켕겼다.',
                effect: { lose: 'cursed_ring', gold: 90, flag: 'ring_passed' } },
        fail: { result: '누구도 사려 하지 않는다. 보기만 하고 손을 젓는다.',
                effect: { hp: -2 } } },
      { text: '부적으로 누른다',
        req: { item: 'charm' },
        result: '은부적을 반지 위에 감아 두자 무게가 사라졌다.',
        effect: { lose: 'charm', flag: 'ring_freed' } },
    ],
  },
  {
    id: 'cb_wolves', place: 'forest', weight: 34, once: true, dayFrom: 8,
    req: { flag: 'saved_pup' },
    title: '따라오는 것들',
    text: '한참 전부터 발소리가 따라온다. 셋. 아니 넷.\n걸음을 멈추자 회색 등이 나무 사이로 드러난다. 가운데 하나는 다리를 전다.',
    choices: [
      { text: '가만히 서 있는다',
        result: '절뚝이는 놈이 다가와 냄새를 맡는다. 그러곤 돌아서서 앞장선다.\n따라간 곳에 사슴 한 마리가 통째로 놓여 있었다. 값이 꽤 나갔다.',
        effect: { gold: 110, item: 'wolf_tooth' } },
      { text: '무기를 든다',
        result: '무리가 물러선다. 절뚝이는 놈만 잠깐 서 있다가 따라 사라졌다.\n그날 밤 잠이 잘 오지 않았다.',
        effect: { flag: 'refused_wolves' } },
    ],
  },
  {
    id: 'cb_pilgrim_pay', place: 'town', weight: 34, once: true, dayFrom: 11,
    req: { flag: 'helped_pilgrim' },
    title: '먼 곳에서 온 사람',
    text: '옷차림이 이 동네 것이 아니다. 당신 이름을 정확히 부른다.\n"인장을 보여 주신 분이 계셨습니다."',
    choices: [
      { text: '인장을 보인다',
        req: { item: 'pilgrim_seal' },
        result: '사내가 고개를 숙이고 자루를 내려놓는다.\n"빚이 있다 들었습니다. 이것으로 되겠는지요."',
        effect: { lose: 'pilgrim_seal', gold: 150, flag: 'pilgrim_paid' } },
      { text: '무슨 소린지 모르겠다고 한다',
        result: '사내가 잠깐 갸웃하더니 돌아섰다. 자루는 가져갔다.' },
    ],
  },
  {
    id: 'cb_ledger', place: 'town', weight: 30, once: true, dayFrom: 8,
    req: { flag: 'stole_ledger' },
    title: '장부를 찾는 사람들',
    text: '여관 주인이 눈짓을 한다. "어제 낮에 셋이 와서 당신을 찾았소."',
    choices: [
      { text: '장부를 돌려준다',
        req: { item: 'ledger' },
        result: '조용히 두고 나왔다. 숫자는 이미 고쳐 놓은 뒤였다.',
        effect: { lose: 'ledger' } },
      { text: '장부를 태운다',
        req: { item: 'ledger' },
        result: '종이가 잘 탔다. 다만 그 사람들이 숫자를 기억 못 할 리는 없다.',
        effect: { lose: 'ledger', debt: -50, hp: -4, flag: 'burned_ledger' } },
      { text: '먼저 찾아간다',
        check: { stat: 'tongue', dc: 14 },
        ok:   { result: '셈을 새로 했다. 어느 쪽도 좋게 끝나진 않았지만 몸은 성하다.',
                effect: { debt: -30 } },
        fail: { result: '문을 열자마자 뒤에서 문이 닫혔다.',
                effect: { hp: -4, debt: 30 } } },
    ],
  },
  {
    id: 'cb_reputation', place: 'town', weight: 26, dayFrom: 7,
    req: { flag: 'killed_yield' },
    title: '수군거림',
    text: '술집에 들어서자 이야기가 뚝 끊긴다.\n"…그 길에서 무릎 꿇은 애를 벴다는."',
    choices: [
      { text: '해명한다',
        check: { stat: 'tongue', dc: 15 },
        ok:   { result: '길게 말했다. 믿는 사람 반, 아닌 사람 반. 그거면 충분하다.',
                effect: { flag: 'explained_kill' } },
        fail: { result: '말할수록 조용해졌다. 결국 나왔다.',
                effect: { hp: -1 } } },
      { text: '아무 말도 안 한다',
        result: '술만 마시고 나왔다. 등 뒤에서 다시 이야기가 시작됐다.' },
      { text: '그 값에 맞는 일을 구한다',
        result: '험한 얼굴이 필요한 자리는 늘 있다. 품삯이 세다.',
        effect: { gold: 60, hp: -3, flag: 'took_dirty_work' } },
    ],
  },
];

/* ---------- 판이 끝난 뒤 남는 것 ---------- */
const MEMORIES = [
  { id: 'm_debtfree', name: '갚아 본 손',  desc: '시작 금화 +25',
    earn: run => run.debt <= 0,
    apply: run => { run.gold += 25; } },
  { id: 'm_thief',    name: '골목의 친구', desc: '도둑들의 표식을 갖고 시작한다',
    earn: run => 'thief_repaid' in run.flags,
    apply: run => { run.items.thief_mark = 1; } },
  { id: 'm_wolf',     name: '숲의 기억',   desc: '늑대 이빨을 갖고 시작한다',
    earn: run => 'saved_pup' in run.flags,
    apply: run => { run.items.wolf_tooth = 1; } },
  { id: 'm_scar',     name: '흉터',        desc: '최대 체력 +2',
    earn: run => run.hp <= 0,
    apply: run => { run.hpMax += 2; run.hp += 2; } },
  { id: 'm_tongue',   name: '닳은 혀',     desc: '말솜씨 +2로 시작한다',
    earn: run => Object.keys(run.flags).length >= 8,
    apply: run => { run.stats.tongue += 2; } },
  { id: 'm_saint',    name: '신전의 이름', desc: '사제의 증표를 갖고 시작한다',
    earn: run => 'gave_priest' in run.flags,
    apply: run => { run.items.priest_token = 1; run.flags.gave_priest = 0; } },
];

if (typeof module === 'object' && module.exports) {
  module.exports = { items: ITEMS, events: EVENTS, memories: MEMORIES };
} else {
  window.QuestData = { items: ITEMS, events: EVENTS, memories: MEMORIES };
}
